### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by sombodi** [deliciousbrains/serialized-editor#1]
verbose get saving serialized-editor to /home/ax4/.npm/registry.npmjs.org/serialized-editor/.cache.json
22 verbose stack TypeError: Cannot convert undefined or null to object
22 verbose stack     at Function.keys (native)
22 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:121:29)
22 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
22 verbose stack     at /usr/share/npm/lib/utils/pulse-till-done.js:19:8
22 verbose stack     at saved (/usr/share/npm/lib/cache/caching-client.js:168:7)
22 verbose stack     at /usr/share/npm/node_modules/graceful-fs/polyfills.js:210

**Comment by gilbitron** [comment]
@sombodi Can you provide us with more details as to what you were doing when this error occurred?
